---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

inputs:
  - name: source
  - name: node-modules

run:
  path: source/ci/tasks/integration.sh
  args: [
    --input-dir, source,
    --module-cache, node-modules
  ]
