---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

inputs:
  - name: pcfdemo

run:
  path: source/ci/tasks/integration.sh
  args: [
    --input-dir, source,
    --hostname,
    --domain, 
  ]
