---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

params:
  CF_MANIFEST_HOST:

inputs:
  - name: source
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-final

run:
  path: source/ci/tasks/prepare.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-final,
    --version-file, version/number,
    --input-manifest, source/manifest.yml,
    --packaging, tgz
  ]
