---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

inputs:
  - name: source
  - name: candidate-release
  - name: version

outputs:
  - name: prepared

run:
  path: source/ci/tasks/prepare.sh
  args: [
    --input-dir, final-release,
    --output-dir, prepared,
    --manifest, source/manifest.yml,
    --packaging, tgz
  ]
