---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: boron

inputs:
  - name: source
  - name: prepared
  - name: version

outputs:
  - name: release

run:
  path: source/ci/tasks/release.sh
  args: [
    --input-dir, prepared,
    --output-dir, release,
    --version-file, version/number,
    --packaging, tgz
  ]
